services:
  db:
    image: mysql:8
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: app
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 30s
      retries: 30
    volumes:
      - db_data:/var/lib/mysql

  seed:
    build:
      context: ./app
      dockerfile: ./deployment/seed/Dockerfile
    container_name: seed
    depends_on:
      db:
        condition: service_healthy
    environment:
      BULK_COUNT: 4000
      USERS_PER_BULK_COUNT: 10000
    links:
      - db

  api:
    build:
      context: ./app
      dockerfile: ./deployment/api/Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  db_data:
